### ISSUE TITLE
Game won't start when computer's uptime is more than 24 days

### ISSUE THREAD

**Issue by paneologist** [TVTower/TVTower#1029]
see also: https://www.gamezworld.de/phpforum/viewtopic.php?pid=90270

32 bit integer overflow in  "SeedRand(MilliSecs())" - MilliSecs seems to give a signed 32bit integer, uptime of the computer in milliseconds. 
after 2^32 milliseconds uptime (2^32/(60*1000*60*24)) = 24.855134815 (days)) the game doesn't start:

[12:43:57] DBG      | ====== PREPARE NEW GAME ======: 
[12:43:57] DBG      | TGAMESTATE.INITIALIZE(): Reinitialize all game objects
SeedRand got passed a negative seed "-2139214231". not allowed.

**Comment by nittka** [comment]
The bug itself can be circumvented by restarting the computer. More problematic to me is that the seed persisted in a savegame is not used at all. Game initialization after loading sets the seed to 0. This problem should be fixed in the PR as well.
You can locally check that by printing the seed in mersenne.bmx when setting the seed and calls to the rand functions.

**Comment by GWRon** [comment]
The bug itself is not a biggy if seedrand allowed negative numbers...or simply casted it to an uint.
Even a "abs(millisecs())" would avoid the issue and still provide a kind of "random initial seed".

That the seed is not persisted would be indeed a real issue ...and I thought it was persisted as else a "quicksave...reload...reload...reload..." would result in different results each time (varying offers, audience quote variations...)
