### ISSUE TITLE
Pressing shift should make ad tooltip show audience by percentage

### ISSUE THREAD

**Issue by jez9999** [TVTower/TVTower#1117]
Currently, pressing shift makes the ad tooltip show profit by block instead of total.  It should also change to show min. audience by percentage rather than as an absolute figure.  Doing it by percentage is often more useful.

**Comment by nittka** [comment]
I don't think that this will work properly. As you have to achieve an absolute number of viewers and the number of potential viewers is different each hour, which value would you want to display?

You could calculate a fixed percentage based on the total number of receivers. But during prime time only a maximum of around 65% (? distributed over all players) of those will be watching at all (much less during night time). Say there are 1 Mio receivers and the ad requires 100K, we could display 10%. This is totally misleading. In the afternoon when only 100K will be watching TV at all, you would have to achieve 100%, at prime time 600K may be watching the real value would still be 16% rather than 10%.

Or would you want to show the percentage based on the current number of potential viewers? When browsing for ads during the night you will have a min audience of 4000%!?

I am open for suggestions, how to calculate the value to be really helpful.

**Comment by jez9999** [comment]
Right, I didn't realize how different it was from the original MadTV where you just had a potential number viewers based on transmitters alone.  I guess percentage of current potential viewers might be helpful?

**Comment by nittka** [comment]
The current proposal shows the required audience rating wrt. combined target groups as well (for code simplicity).
