### ISSUE TITLE
Configurable Betty rating override needed

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#1169]
So for many (cultural) programmes and news, a Betty bonus is determined automatically.

But sometimes we need to override this for specific programs.

Most prominent example: "Kultur Heute". In Mad TV, it always achieved a 0% audience result. It doesn't have to be that bad in TVTower, but it should still fare among the worst. However, critics is set to 100%, probably to achieve best possible Betty outcome, but that will also cause the show to fare pretty well in general.

Hence, it would be good if the ratings for "Kultur Heute" could rather be configured something like this:

`<ratings critics="5" speed="9" outcome="1" betty="100" />`

Note it should mean the best possible Betty result possible in the game, regardless of how well it does with the audience. It has to do better than an any other cultural program with high critics rating and magnificent audience results.

A counter example could be a cultural programme that Betty really dislikes for some reason. Maybe because it's moderated by some bitch she hates. Then, for example, `betty="-50"` could be set.

Then, there is automatic Betty malus for Erotic programs, even if Erotic is just the 2nd or 3rd subgenre. However, for humor reasons, it turns out that Betty doesn't mind at all if it's "Erotic for women", like in some existing entry by TheRob, or perhaps a [Chippendales](https://en.wikipedia.org/wiki/Chippendales) show. Then `betty="0"` could be set (though it has to mean that there should be no effect on the Betty rating, and *not* that the parameter is ignored and not set at all to be determined automatically).

Note that the "absolute" Betty value needs to be possible to configure here, not a "mod" that would effect only some relative change.

**Comment by nittka** [comment]
One effect, you can already influence. The broadcast flag 2048 (ignored by Betty) should reduce negative and positive values for a broadcast to 0 (for paid, erotic or culture programmes, as well as culture news). Of course, this does not allow you to add a Betty value change to a programme.

For explicit changes, I am not yet sure whether a rating value as proposed by you is best or an effect (analogous to programme availability or person popularity). The effect version might have the advantage of being more flexible (first broadcast, each broadcast). Maybe effects could also be added to ads, as well ...

**Comment by scr0llbaer9000** [comment]
> The broadcast flag 2048 (ignored by Betty)

Ah, alright, thanks, that's applicable to TheRob's example.

**Comment by nittka** [comment]
Work on time delayed effects may have helped. There is already a game internal modify betty love effect. As the player broadcasting a programme/news is needed for the effect, some small change on triggering the effect will be needed but then it should be possible to write something like `<effect trigger="broadcast" type="modifyBettyLove" valueMin="0.02" />` (syntax/value range not fixed, yet).

**Comment by nittka** [comment]
I have a working prototype (https://github.com/nittka/TVTower/tree/bettyModifier) for an effect that adds a random percentage (in a min max range) for each broadcast (or even only on the first broadcast). When looking at the betty code, I still see some problems that could be addressed by different approaches.

The number of points earned 
* does NOT take the reached audience into account (so you could send culture programmes during the night without much loss but make Betty just as happy)
* is based on "overall quality" which includes all attributes (topicality as well) not only the critics value.

I'd like to introduce a time dependent modifier for the (earned) points, e.g.
* 1.25 during prime time
* 0.75 during night time
* 1 otherwise

Making the points directly depend on the audience number (quote does not suffice, 40% at 3 am is very different from 40% during prime time) seems to raise too many issues. (Lost points due to flags/genre are fixed values at the moment - I'd have no problem leaving it that way.)

With the igore-Flag, you can completely disable any betty love change.
With the (existing but currently broken) betty effect (see branch for repair and usage example) you could define (additional) changes on the first/on any broadcast (but independent of topicality/quality/time of broadcast).
With a new modifier type (we have a terminology problem here) analogouse to "topicality::age", e.g. "betty::relativeFactor" we could change the calculated value. 1 would change nothing, 2 would double the earned/lost points, -1 would negate the value.
If we need an additional modifier betty::disableTimeBasedFactor or something like that can be discussed.

Syntactically, effects and modifiers are already supported by the database which is why I would prefer those two options over a new data-field "betty" with exactly one possible interpretation. What you could achieve with them is more flexible, even if you need to write more database code.

**Comment by scr0llbaer9000** [comment]
ok, a modifier would be fine in some cases, but as pointed out, the point of "Kultur Heute" in Mad TV and the joke was that it always achieved maximum betty love, regardless of any other outcome (and with proper flags can only be broadcasted once per edition, has to be produced anew; have to recheck).

**Comment by GWRon** [comment]
A flag could tell to ignore audience ratings. Or instead of a relative gain it has an absolute gain..

**Comment by nittka** [comment]
I did not mean exclusive approaches. I will add the modifyBettyLove effect first and then work on the other issues.

By the way, a 1% increase is the maximum you can currently achieve (with a culture program with maximum quality and topicality). It is a bit questionable that the points are divided by the number of blocks at the moment (i.e. a 12 hour 100% programme would earn 1% betty love - the same as a 1 hour 100% programme). I guess, it does not make that much difference with few culture programmes longer than one block.

The betty love effect would allow you to ignore the calculated change (set ignore flag) and only cause a fixed percentage change (minValue="150" maxValue="150" for a 1.5% increase).

**Comment by nittka** [comment]
Betty point change can now be defined as effect in the database (update of documentation will follow soon).

**Comment by nittka** [comment]
I am playing around with modifiers analogous to `topicality::age` for betty. My suggestions would be
* betty::basepointsabsolute - rather than using the points based on the programme quality (or flags/genre) use this value (excluding 0, here the ignore betty flag should be used); further time modifers etc. will be applied
* betty::pointsmod - base factor for the final point value (default 1); time and live will still be applied
* possibly betty::basequality - rather than using the calculated quality use basequality*topicality (e.g. for "Kultur Heute" - actual quality is bad but Betty likes it; topicality factor will still be applied)

**Comment by nittka** [comment]
It really depends on the effect you want to achieve
* restrict to one broadcast - fixed betty effect or betty base modifier for higher calculated score
* allow multiple broadcasts but define betty effect on first broadcast only (many points first time, few afterwards)
* allow multiple broadcasts with higher betty base modifier
* something intermediate - multiple broadcast, medium betty base modifier, but additional fixed points on first broadcast
