### ISSUE TITLE
Some names defined with `<all>` in news are still not resolved to German

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#1246]
"Gorbochov" has a version in the German language file as "Gorbotschew", but that does not show up when playing in German.

![gorbochov](https://github.com/user-attachments/assets/274962f3-5b7f-47cd-bae8-14b4ba9ba882)

Definition for that news item is:

		

	<news guid="90ee7429-32a6-43ad-a2cd-5d1a61bfbc1f" type="0" creator="8936" created_by="jorgaeff" comment="KPdSU, CPSU, Michail Sergejewitsch Gorbatschow, Mikhail Gorbachev - https://en.wikipedia.org/wiki/Mikhail_Gorbachev#General_Secretary_of_the_CPSU">
		<title>
			<de>${gorbachev} wird ${generalorg_cpsu}-Generalsekretär</de>
			<en>${gorbachev} becomes ${generalorg_cpsu} Secretary General</en>
			<pl>${gorbachev} zostaje sekretarzem generalnym ${generalorg_cpsu}</pl>
		</title>
		<description>
			<de>Im Alter von 54 Jahren wird ${mikhail} ${gorbachev} zum jüngsten Generalsekretär in der Geschichte ${generalorg_ofthecommunistpartyofthesovietunion} (${generalorg_cpsu}) gewählt.</de>
			<en>At the age of 54, ${mikhail} ${gorbachev} is elected the youngest General Secretary in the history ${generalorg_ofthecommunistpartyofthesovietunion} (${generalorg_cpsu}).</en>
			<pl>W wieku 54 lat ${mikhail} ${gorbachev} zostaje wybrany najmłodszym sekretarzem generalnym w historii ${generalorg_ofthecommunistpartyofthesovietunion} (${generalorg_cpsu}).</pl>
		</description>
		<variables>
			<mikhail>
				<all>${.person:"6dd0a9b9-96a0-4712-83f0-f6388bdc5bec":"firstname"}</all>
			</mikhail>
			<gorbachev>
				<all>${.person:"6dd0a9b9-96a0-4712-83f0-f6388bdc5bec":"lastname"}</all>
			</gorbachev>
		</variables>
		<data genre="0" price="0.8" quality="80" fictional="0" flags="2" happen_time="5,1985,1985,1,6,1,30" /> 
	</news>

So the variable is defined with `<all>`.

Happens reproducibly every time when starting a game in 1985.

Later in the game it seems to work (sometimes?).

**Comment by nittka** [comment]
I think this is a conceptual problem (not clear yet, if solution is easy). The name localization behaves differently than the other Strings (title, description). Person names are not localized strings but simple strings. So at the point of news creation, the same name is stored in the variable for all languages (it makes no difference if you use all or de, en and pl). The .person function retrieves the name from the actual person. On changing the language, the person names are replaced by the new language - but the variables have all been set before...
This is a problem that primarily affects games where you change the language. If you start with one language (and don't want to change it), it should not matter to you, that the names are the same in all languages.

The second problem is (probably) that the initial game language is set only after the news with fixed happen time (even far in the future) are generated. In the above case the English name version will have been used before the name was changed to German.
This probably could be fixed by changing the order. Read database, set language, then create fixed time news entries.

With the introduction of the database localizer for persisting the lang entries it might be possible to solve the first problem. When resolving a person/role function, it is also checked whether a localization exists, in which case that data is used rather than the "simple" string.
