### ISSUE TITLE
Live show defined with `year_relative_min="2004"` already shows up in 1987

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#1247]
So it seems that https://github.com/TVTower/TVTower/pull/1167 should have been applicable for live shows in general?

![bbw](https://github.com/user-attachments/assets/63125ec4-c621-4ed8-a9c5-9a581d4d3d14)

"Best of Bolivian Wrestling I" is defined as:

`<releaseTime year_relative="3" day="1" hour="20" year_relative_min="2004" />`

But it already shows up in 1987 (when starting to play in 1985).

**Comment by GWRon** [comment]
Code is:
```
		MathHelper.SortIntValues(releaseYearRelativeMin, releaseYearRelativeMax)
...
		'= YEAR =
		If releaseYear = 0 Then releaseYear = GetWorldTime().GetYear() + releaseYearRelative
		If releaseYearRelativeMax = 0 Then releaseYearRelativeMax = releaseYear
		releaseYear = MathHelper.Clamp(releaseYear, releaseYearRelativeMin, releaseYearRelativeMax)
```
Sorting makes `releaseYearRelativeMin` (2004 in the DB) become 0 and `releaseYearRelativeMax` now 2004.

So `releaseYear` becomes current (1985 as start) + `releaseYearRelative` (+3 = 1988)
`releaseYearRelativeMax` is now defined (was undefined but sorting made it 2004) -> no change
`releaseYear` (1988) becomes clamped between 0 and 2024)
-> releaseYear should stay at 1988

Debug-stepping-through says: yep, 1988 is the release year.

![image](https://github.com/user-attachments/assets/40539402-bc19-4559-ad51-519576b64a40)


Maybe some stuff like "live" takes over here? There are release cycles (cinema, retailer, tv ...) and maybe such stuff interfers here.

**Comment by GWRon** [comment]
```


	Method GetReleaseTime:Long()
		Return releaseTime
	End Method


	Method GetCinemaReleaseTime:Long()
		Return releaseTime - Max(1, GetWorldTime().GetDaysPerYear()/2) * TWorldTime.DAYLENGTH
	End Method


	'only useful for cinematic movies
	Method GetProductionStartTime:Long()
		Return releaseTime - GetWorldTime().GetDaysPerYear() * TWorldTime.DAYLENGTH
	End Method
```
So Cinema is 6 days earlier and production start is 1 year earlier.

Will have to check if game.roomhandler.movieagency.bmx `Method GetNextOffers:TProgrammeLicence[](includeFilters:TProgrammeLicenceFilter[], excludeFilters:TProgrammeLicenceFilter[], amount:Int=1, list:TObjectList=Null, maxEroticCount:Int=100)`
somehow is called with custom "includeFilters" ... because then the following filters are not applied:
```
				If Not p.IsTradeable() Then Continue
				If Not p.IsReleased() Then Continue
```


and it is called this way:
```

				Select lists[listIndex]
					Case listMoviesGood
						licences = GetNextOffers([filterMoviesGood], Null, needed)
						'licences = GetProgrammeLicenceCollection().GetRandomsByFilter(filterMoviesGood, needed)
					Case listMoviesCheap
						'exclude the good movies
						licences = GetNextOffers(Null, [filterCrap, TProgrammeLicenceFilter(filterMoviesGood)], needed, Null, 2 - cheapEroticCount)
						'licences = GetProgrammeLicenceCollection().GetRandomsByFilter(filterMoviesCheap, needed)
					Case listSeries
						licences = GetNextOffers([filterSeries], [filterCrap], needed, offerPlanSeriesLicences)
						'licences = GetProgrammeLicenceCollection().GetRandomsByFilter(filterSeries, needed)
				End Select
```
Means "filterSeries" and "filterMoviesGood" are responsible for filtering out "released".

These filters are only assigned "checkTradeability = True". These filters for now do not allow defining "checkReleased" ... so the "is released" is simply ignored for them.

I am running out of time now - but I assume it also somehow takes into consideration if the licence is "at least in cinema" (which would explain just popping up 1987, not already 1985.

Will have to investigate further...

**Comment by GWRon** [comment]
I guess another thing happening here is:

The movie agency holds its own list of elements it could "offer".
As soon as a programme licence changes ownership .. an event is emit which the movie agency listens to.
If the licence owner is nobody, it gets added to that "offer pool", and if it owned now by someone then it is removed from there.

On Start (or when loading an old savegame which does not contain the offer list already) this list is filled because the owner of all programmes are set to "nobody" (not owned).

Thus leads to eg this entries here being added:
```
OFFER: add 2001 Affenerde    RELEASED=0
OFFER: add 1992 Alarmstufe: Seeehr Dringend!    RELEASED=0
OFFER: add 1964 Old Smasherfist    RELEASED=1
OFFER: add 2000 Am sechsten Tag erschuf...    RELEASED=0
```

This means the list contains ALL licences and is "unfiltered". This also means ... we need to either extend the filter to include the ability to enable/disable checking for "is released".
Or we do not allow these filters to do so and by default filter out any "not released" ones --- thus limiting ourself - guess this is not the option to go.

Maybe best is to have the "is released" check "on" by default in the filters - and thus only on special interests one disables that check - on purpose.

**Comment by GWRon** [comment]
@nittka I here request your assistance - but more in the sense of a helper/opinion sharer:
Filters already have:
```
	Field checkAvailability:int = True
	Field checkTradeability:int = False
```

And checkAvailability defaults to "True" (so was enabled in the filters).
Now "isAvailable()" has this comment:
```
	Method isAvailable:int() {_exposeToLua}
		'checking for isReleased() hides "live" programme"
		'also: GetData().isAvailable() calls data.isReleased() already
		'if not isReleased() then return False
```
The comment is from me and was added 8years ago:
https://github.com/TVTower/TVTower/commit/d92553f8ff747182ce27e59bdd457759409b9b33

I guess from this commit on, "IsAvailable()" was no longer linked to "(licence.)IsReleased()".
But as you see in the comment: "licence.(programme)data.IsReleased()" is still checked

Now for the programmedata (@scr0llbaer9000 these are things about the programme (title, cast, values,... "topicality") licences could share ... licences are the ones who can restrict broadcast counts etc) the IsAvailable-Method (which the filter indirectly calls by calling licence.IsAvailable()) differs:

```
	'override
	Method IsAvailable:Int()
		'live programme is available 10 days before

		If IsLive()
			'TODO the alwaysLive-Flag of the header is not set
			'but if it was, the header would not be available anymore as then the "released"-check fails
			'print getTitle() +" available?" + " "+isHeader()+ " "+ isReleased()+ " "+ isAlwaysLive()
			If IsAlwaysLive()
				'is a default case - available after release
			Else If GetWorldTime().GetDay() + 10 >= GetWorldTime().GetDay(releaseTime)
				Return True
			Else
				Return False
			EndIf
		EndIf

		If Not isReleased() Then Return False

		Return Super.IsAvailable()
	End Method
```

"IsAvailable" now means "is existing" (so eg is in (pre)-production ...).
The code here uses a fixed amount of 10 days it subtracts from the release time. So 10 days before "first wrestling match" the licence for it is offered.

Ok, back to the assistance request: What is your opinion on adding an "checkReleased:Int = True" to the filter? Not helpful "here" but maybe "useful".

And ... what about the 10 days. Maybe we should instead change to `GetProductionStartTime()` (this was not existing that time I guess). This would allow to change this "GetProductionStartTime()"-result depending on the production type (eg sport series do not need so much pre-production compared to "hollywood series" or so).

**Comment by scr0llbaer9000** [comment]
> it is (code wise) OK for the licence to be offered some days earlier (here 10 game days).

10 days in advance is okay but not 20 years `;)`

**Comment by scr0llbaer9000** [comment]
Would `-1` for max have helped or same problem? Otherwise, no specific max date desired here. Has an annoying effect on live shows (maybe I'll open another issue).

**Comment by GWRon** [comment]
No it wouldn't have helped.

The issue was that it sorted min and max and if max was smaller...then 2004 would have become the new max.


The PR I provided should fix it. Awaiting confirmation of nittka. (Feel free to try on your own)

**Comment by nittka** [comment]
I think, the fix for calculating the correct release year is enough. Live programmes have to be available in the movie agency a bit before the actual release, otherwise there is no chance to broadcast them live. Making the time for that configurable seems overkill at the moment. I'd close the ticket after merging the PR.
