### ISSUE TITLE
English Translation of Manual

### ISSUE THREAD

**Issue by MatthewForrester** [TVTower/TVTower#348]
Hi! I am Matthew from GamezWorld.

I enjoyed this game, but I didn't understand everything. So I have started translating Själe's manual into English, in the open-source spirit that "if it doesn't work, fix it!"

My [*english-manual* branch has an unfinished draft](https://github.com/MatthewForrester/TVTower/blob/english-manual/docs/manual_en.md) (in UTF-8 with Unix line endings) using British English except for the words used in the UI, which I have left in the original Denglish. 😝 (Having said that, I really appreciate your kindness in translating everything in the UI into English!). Is that what would you were like? I will leave any UI changes and manual updates for the future.

I am certainly not a professional translator, so there are probably errors. It's been fun to finally use my high school German for something useful though. I checked my draft translation against Google Translate. I was not surprised that Google appeared to understand some parts I could not or that we often had exactly the same translation. But I was embarrassed how many times the machine's translation had more natural and fluent English than mine! 😳

There are still a few places where I need your help, please, especially where I am trying to understand the German humour 😝, which I would like to keep in the translation.

> Das ist der Mann für's Grobe.

Is the meaning something like "this person is very bad because he behaves in a very impolite way", please?

The Internet tells me this is the name of a Frank Zander song. Is the phrase only famous because of the song? Maybe I will link to the song.

> Der tut allerdings nicht zur Sache.

Is the meaning here "the previous sentence [about cigar smoke] is not important"? Or "the boss does not follow the rules"?

> Film(e)

Does the German word include a show like «Morgenmagazin»? Or were these shows added to the game after the manual was written?

> Die Terrorgefahr wird im späteren Verlauf mit einer Nachricht angekündigt.

Can I please check that "Terrorgefahr" is talking about the *possibility* of terrorist attacks? It is *not* saying that an attack has happened?

Thank you for the game and your co-operation!

**Comment by GWRon** [comment]
Hi Matthew.

First of all: thanks for your efforts.

Regarding "Denglish" ... feel free to improve these parts too (gameDirectory/res/lang --> feel free to adjust to "correct BE").

Regarding "google translate" ... maybe give deepl.com a try, it is said to be even better in many cases (for German<->English).


> der Mann für's Grobe
You say this about a man which is hired for the ... non-chalant ways of doing things. Maybe "strongman" or "hatchet man" would be a good translation.

> Der tut allerdings nicht zur Sache.
First of all there is a Grammar mistake. It should be "Der tut allerdings nicht_s_ zur Sache" (and the "tut" is not the best choice of words :D).
As you already understood right - it is saying that "it" (the cigar smoke" is unimportant.

> Film(e)
The manual generalizes the term "Filme" a bit too much. Normally you would better write about "Programme licences". But as you are going to the "movie dealer" (Filmhändler) instead of a "Programme Licence Dealer" it might suit to describe them as "movies".
So if translating "Filme" as "movies" and playing strict, then "Morgenmagazin" (or any other "show"/talk/series) would not be "meant".
When it is to distinguish between "movies", "series", "shows" ... then the individual terms are to prefer.

In the case of the manual it might be still a good thing to also replace these "Filme" here and there with more suiting words.

> Terrorgefahr
Yes - it is the danger of terror happening - not of something already happened (this would then be the "terror attack" or similar terms).



Thank you for the efforts (to enclose my reply in "thanks" :))

**Comment by GWRon** [comment]
I used the chance to replace some "Film" with "programme/programmelicences".
(and some "daß" with "dass" - Själe seems to prefer the old spelling rules of pre-1995)

**Comment by MatthewForrester** [comment]
Thank you so much for the help. I am updating the draft with these changes. 

> Regarding "google translate" ... maybe give deepl.com a try, it is said to be even better in many cases (for German<->English).

I think you are right; my initial tests suggest that DeepL is even better. A useful discovery!

> Normally you would better write about "Programme licences". But as you are going to the "movie dealer" (Filmhändler) instead of a "Programme Licence Dealer" it might suit to describe them as "movies".  
> So if translating "Filme" as "movies" and playing strict, then "Morgenmagazin" (or any other "show"/talk/series) would not be "meant".  
> When it is to distinguish between "movies", "series", "shows" ... then the individual terms are to prefer.  
> In the case of the manual it might be still a good thing to also replace these "Filme" here and there with more suiting words.

OK, so the German `Filme` is used like the English `films`/`movies`.

I have changed `film(s)` to `programme rights` as the translation for `Programmelizenz(en)`. I know that `programme licence` would be the obvious translation, but `licence` is much more often used for two other things that users may expect to see in a TV game:
* A TV company needs a `licence` from the authorities to operate in all the English-speaking countries.
* The British equivalent of the _Rundfunkbeitrag_ is called the television licence.

I have [collected evidence for the different options](https://gist.github.com/MatthewForrester/caa824f1c12e1ea05a08bf0bd4789071) and I think `programme rights` is the best choice. This is what the TV industry uses and ordinary people know it because of situations like `Amazon now has the rights to my favourite show`.

> (and some "daß" with "dass" - Själe seems to prefer the old spelling rules of pre-1995)

Those are the rules that were used in all my schoolbooks so I never noticed.
Anyway, I am never going to criticise German spelling when the English rules are soooo crazy.  :flushed:

**Comment by GWRon** [comment]
It is really useful to have you as native English speaker checking through the texts.

I used "programme licence" as I also thought of "software licence" but maybe this is more an "individual" thing (even for volume licences) while the rights allow for a bit more.

Even in Germany you can have Nutzungsrechte (rights to use something) but was not sure if ut perfectly suits here.

We should create a list of such words...to improve the English translation.

**Comment by nittka** [comment]
As the German manual has been updated as well, could you rebase your branch and create a pull request? This will simplify giving feedback and incorporating your translation.

**Comment by nittka** [comment]
I have taken Matthew's branch, rebased and squashed the changes and did a rough first proof reading of the translation (new commits). See https://github.com/TVTower/TVTower/tree/english-manual
