### ISSUE TITLE
Update Compilation Guide?

### ISSUE THREAD

**Issue by MatthewForrester** [TVTower/TVTower#350]
I am able to build and run TVTower using the following instructions:
1. Install BlitzMax-NG
2. Run BlitzMax/MaxIDE
3. Load TVTower.bmx
4. Click "Build and Run" (Ctrl+R)
This is very easy (no makefiles etc.) and encouraging. Thank you, team BlitzMax!

I then tried:
5. Click "Build".

It appeared to compile, but I have some questions.

I found the [compilation](https://github.com/TVTower/TVTower/blob/master/Misc/documentation/compilation_guide.txt) [guides](https://github.com/TVTower/TVTower/blob/master/Misc/documentation/compilation_guide.LINUX.txt), but they have not been updated for many years. Maybe it would be helpful to add the answers to the compilation guide or to [README.md](https://github.com/TVTower/TVTower/blob/master/README.md).

I am using Ubuntu 20.04.2.

#### Build path
Where does MaxIDE output the build, please? I checked `BlitzMax/tmp`, `/var`, `/tmp`, and the TVTower repo, but could not find it. The MaxIDE `IDE Options` do not have an output option. The pre.bmk file contains a `%BUILDPATH%` variable, but....

#### pre.bmk and post.bmk
MaxIDE does not recognize these files. [This helpful page](https://blitzmax.org/docs/en/language/pre_post_compilation_scripts/) on the BlitzMax website explains that they are build scripts (like makefile) and how to write them, but does not explain how to call them. I read [the bmk manpage](https://blitzmax.org/docs/en/tools/bmk/), but it just refers to the page above. It seems to assume a single source file, but I think we want to call `pre.bmk TVTower.bmx post.bmk` in that order, right?

**Comment by GWRon** [comment]
Yes the compilation guide was based on an early version NG and the legacy version (vanilla blitzmax). And also the TVTower code of that time was trying to be compileable with NG (for 64bit) and legacy (for 32 bit - as legacy was developed over many years and might have been more bug free).

But since some months TVTower is only built with NG - and so is also only tested with these builds.

---

When "Build n Run" it compiles the binary and executes it. The binary is placed right in the same directory as the "TVTower.bmx".
On Windows it would be named "TVTower.exe", on Linux "TVTower" and on Mac it would be located in the "TVTower.app"-folder (Mac OS "applications" are folders - containing information files, icon files and the binary).

The "build files" are in "TVTowerfolder/.bmx" (but also in "TVTowerfolder/sources/.bmx" - it is creating this subfolder for every folder it compiles source source in. There it stores the generated C-code, the compiled C-code, interface files etc.


The "pre.bmk" is automatically interpreted by "bmk" (the file you use to call the "application compilation" which then calls "bcc" which is the actual c-transpiler). It is interpreted before the first file is "to compile" (so you can use it to eg manipulate your file to contain a current timestamp in the version string or so... I do this differently, via an '@bmk command in the project files).
The "post.bmk" is automatically interpreted by "bmk" after compilation is done. We use that to strip unnecessary stuff from (release) binaries. I also use it to rename binaries accordingly ... this is why a 64 bit Windows build results in
"TVTower.exe" but also in "TVTower_Win64.exe" (they are the same files).

So yes it is kinda like calling 
pre.bmk
compile TVTower.bmx
post.bmk

**Comment by nittka** [comment]
How about moving the compilation guide to the documenation repository (and linking it in the readme). I also don't know how upto-date the rest of the documentation directory is.

**Comment by GWRon** [comment]
We could do so.

**Comment by nittka** [comment]
Moving the compilation guide is addressed with #457. A branch/ticket in the documentation repository has been created.
