### ISSUE TITLE
Keyboard shortcut L does not work

### ISSUE THREAD

**Issue by MatthewForrester** [TVTower/TVTower#353]
**Steps to reproduce**
1. Download release 0.7.0 or build from the latest commit 983f476 in MaxIDE
2. Load a save game
3. Press the "L" key

**Expected behaviour**
The Supermarket screen opens, as described in the Manual

**Actual behaviour**
Nothing happens

**Comments**
The keyboard shortcut is set in [/source/main.bmx line 1319](https://github.com/TVTower/TVTower/blob/983f476eff3d33bcb6b90e81392cc46b3ed7b0b5/source/main.bmx#L1319), in `__NonDevHotKeys`. 
But it is not set in `__DevHotKeys` shortcuts, where a different shortcut (LCONTROL+S) [is set.](https://github.com/TVTower/TVTower/blob/983f476eff3d33bcb6b90e81392cc46b3ed7b0b5/source/main.bmx#L1231).

At the moment the game either runs `__NonDevHotKeys` or `__DevHotKeys`. (Though `__NonDevHotKeys` calls several "DEV_" variables, e.g. [line 1346](https://github.com/TVTower/TVTower/blob/983f476eff3d33bcb6b90e81392cc46b3ed7b0b5/source/main.bmx#L1346)). And there is a third set of keyboard shortcuts which [always run](https://github.com/TVTower/TVTower/blob/983f476eff3d33bcb6b90e81392cc46b3ed7b0b5/source/main.bmx#L687).

This is technically 'works as designed', because at the moment everybody is playing in Dev mode. But if new players are expected to use Dev mode, then the manual should say what actually works in the game now.

**Quick fixes**

- Remove the L shortcut from the manual
- Add the L shortcut to `__DevHotKeys`

**Long-term solution?**
Maybe the "NonDev" shortcuts should always be called, so that any bugs can be caught as soon as possible. Then the additional "Dev" shortcuts should also be called in Dev mode.

Is there a technical reason why the two sets of shortcuts are "either/or", or is it just an accident of history?

**Comment by nittka** [comment]
This issue is closely related to #186 (sorry that it is in German, but as you have worked on a translation of the manual, you may get the gist of what the ticket is about). When working on 0.7, we discussed shortcuts for a final (or non-developer) version. My argument was that having shortcuts with modifiers (s for studio vs ctrl-s for supermarket) should not be used in the long run. A first proposal was made and implemented (common short cuts, backward compatible developer shortcuts, new proposed player shortcuts - actually with a different implementation as well; no "beaming" to the room, but walking).
The manual has not really been revised for 0.7, only some minor modifications were made, hence #186. There are features in development mode that should not be present in a final version (tab, cheat commands via chat,...) - at least I think so, but it is not yet settled, what is development only. The two sets of shortcuts are not an accident of history but the start of separating development features (wrt shortcuts) from the final result.

It may also be argued that when releasing a new version, the dev-keys-flag should be set to false by default; in which case the manual will have to be updated definitely, because the speed modification keys will work not at all or rather differently.

**Comment by MatthewForrester** [comment]
Thank you for explaining the reason why there are two sets of shortcuts. Naturally there are many areas of the game that are currently under development.

It appears this issue is almost a duplicate of 186, for which I apologize. 

My work is focused on the manual. So I think I will add a note to both manuals stating that this shortcut is currently disabled in the Developer Version. The manual can be updated again after issue 186 has been closed.

>  (sorry that it is in German, but as you have worked on a translation of the manual, you may get the gist of what the ticket is about)
Yes, I can read issues in German (with help from Wiktionary). I am grateful for your kindness in replying and writing code comments in English.

**Comment by nittka** [comment]
No need to apologize. The manual is plainly wrong, maybe it would be better to leave out the L-shortcut for now, because the "new" one for the script agency (D) ist also not mentioned. We could also add a section explaining about the non-developer mode.

**Comment by nittka** [comment]
I adapted the code and the documentation. Note that activating both dev- and non-dev keys at the same time does not work. Although in many cases the same keys are used for the same room, the effect is different. In dev-mode you immediately jump to the room, in production mode, you still have to walk (but you need not select the room in the elevator).

**Comment by nittka** [comment]
The keybindings L for supermarket and D for Script agency have been added to the dev-keys. The German manual has been updated accordingly. 
It would be nice, if you could rebase and update your manual-branch. Feel free to create a pull request, which should simplify giving feedback.
