### ISSUE TITLE
News items don't pass on template/variable context in news threads.

### ISSUE THREAD

**Issue by scr0llbaer** [TVTower/TVTower#836]
I have a news thread in which I had to comment out variables I wanted to use.

        <news id="9c58c119-6d16-41fa-9a58-76c5824099aa" type="0" thread_id="51b23dcb-0069-4435-936a-33c6973491c2" creator="9551">
            <title>
                
                <de>Wal in Themse gesichtet</de>
                <en>Whale sighted in Thames</en>
            </title>
            <description>
                <de>Da staunten die Anwohner an den Ufern des Flusses nicht schlecht, als sie am frühen Morgen lautes Platschen und hoch aufspritzendes Wasser bewundern durften.</de>
                <en>The residents on the shores of the river were amazed when they witnessed loud splashing and high spraying water in the early morning.</en>
            </description>
            <data genre="4" price="1" quality="60" fictional="1" />
            <effects>
                <effect trigger="happen" type="triggernews" time="1,10,15" news="92598126-f227-4fd2-894e-a5902eaeb392" />
            </effects>
            
        </news>

The template/variable context is not passed on to the next news item in a thread (which I think shouldn't be much of a problem to implement?), the variable names will not be resolved and will be printed as plain text. Hence variables are for now usable only for single news items.

**Comment by nittka** [comment]
This is indeed a very important enhancement. It would allow for less repetitive news. In particular with respect to referencing persons in the database. It would be nice to resolve these variables in the news' effects as well (raise/lower popularity of an actor because they were seen somewhere).

**Comment by nittka** [comment]
Work is in progress. A prototype-branch exists. The resolution mechanism is currently refactored.

**Comment by nittka** [comment]
I have extracted this part from the general "referencing persons everywhere"-PR, because that might be delayed due to the script expressions refactoring.

In the first version you have to define all variables in the initial news entry, even if not all variables are needed, yet. Those variables (including the chosen variants) will be propagated to the triggered news. That is, triggered news may not define further variables. This should hardly be a restriction. (The special case of self-triggering news like stocks work fine, though.)
