### ISSUE TITLE
I18n & L10n for person names

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#887]
I stumbled over these entries.

		<person id="1994aa3a-23c3-48ce-b20a-d1f021df8c63" first_name="Königin Svetlana" last_name="von Schweden" nick_name="" bookable="0"/>
		<person id="2994ff3d-ffc4-f8ce-c25a-e1g0d1df8c64" first_name="ein Arbeitsloser namens" last_name="&quot;Groggy&quot;" nick_name=""  bookable="0"/>

For versions in other languages, there needs to be a way to translate these.

These are not only 2 edge cases in the game, there are plenty of examples of real people who have names that are spelled differently in different languages and that may become relevant, e.g. Mikhail Gorbachev / Michail Gorbatschow / Михаи́л Горбачёв.

Also a lot of the name-faking/spoofing that has so far been applied to the actors in the data today only work for a German audience ("Brus Will-Es").

Maybe it's already possible to apply language tags if these person entries are converted from "insignificant" to "significant"?

**Comment by GWRon** [comment]
Hmm ... I assume the localization only needs to be done for non-fictional persons. And most of the times we do not need more than a single "fake name".
Yet this also means we need to localize "all parts" of the name.

Also I am not sure who is willed to rewrite all the person names into foreign char-sets. Not to talk about the persongenerator-code which spits out the random/fictional person names.
I fully understand it for the "Königin Svetlana von Schweden" though.

Am not sure if we should use our "TLocalizedString" for it.



Regarding Svetlana von Schweden: if we did it in a Script it would mean we should add a new category of "cast": "VIP guests" which are only available for certain formats (you cannot make them "actors" or so - like you can do with other cast candidates).

**Comment by nittka** [comment]
I also have the feeling that extending the database syntax in order to allow full localzation of all person name attributes would be overkill for a handfull of cases.
What about the following approach: rather than putting all language versions into one file, there are specialized "localized" databases for persons. These will be loaded on top of the "base" database, possibly changing the name attributes of selected entries.
When loading a game or when changing the language, the corresponding localized database asked to update existing entries.

**Comment by scr0llbaer9000** [comment]
> there are specialized "localized" databases for persons. These will be loaded on top of the "base" database, possibly changing the name attributes of selected entries.

That would be fine with me.

**Comment by nittka** [comment]
Going through the big database review PR, I am wondering if a similar problem exists for roles (different localized versions and original names).
Currently, it is not possible to referenece a role in the programme cast. The news PR contains an extension of the database syntax for defining a role ID in programmes as well (I think this is more appropriate than linking a "global role" in the description directly).

A low-tech approach would be to update role names just like person names using a localization file. And if you want to play with real names, you have to replace the localization file with one containing the original role names.

**Comment by nittka** [comment]
A prototype implementation now exists.

**Comment by scr0llbaer9000** [comment]
> I am wondering if a similar problem exists for roles (different localized versions and original names).

Yes, definitely, probably there will be many more instances than with real people names (e.g. "Klopfer" vs "Thumper" in "Bambi").

> And if you want to play with real names, you have to replace the localization file with one containing the original role names.

Just like with the person data, there can be the `first_name_original` etc XML tags.
A localized file would contain these too, as the spoofing will need to be localized too.

**Comment by nittka** [comment]
Actually, my intention would be not to extend the syntax for roles. I propose to use two directories within the database base directory. "lang" which is actually processed for localizing persons and roles and "lang_original" which is ignored by the game and contains the original names (for those entries that really need different versions).
Rather than having to replace the tags within the files, you simply rename the directories.

I think it would be overkill to go through ALL programmes and add the roles. This should be done only for the significant ones which are being used multiple times (and which are needed for title/description).

**Comment by scr0llbaer9000** [comment]
> Actually, my intention would be not to extend the syntax for roles

It seems `_original` tags (and any that the software doesn't know) are ignored anyway?

> I propose to use two directories within the database base directory

Are you intending that only for the roles, or also for persons, and for everything else too?

That would mean that I would also have to change the approach I have applied so far for my own local data. You mean you would generally prefer that all `_original` tags be removed and put into separate files?

Just changing directory names sounds it would it make it easier for end users, and I like that, but perhaps much more of a problem for contributors and maintainers to essentially maintain two different sets of almost all data.

If using a directory renaming approach, it would be slightly better if there's a separate file/directory that can optionally be activated and that contains the original titles and names, but it would be evaluated *additionally* and in a second step, and for the already existing entries with the same ID it would only overwrite or "patch" the content XML attributes that are specified, and leave the ones of the XML attributes that are *not* specified (like `country` etc) (i.e. not reset them).

**Comment by GWRon** [comment]
> If using a directory renaming approach, it would be slightly better if there's a separate file/directory that can optionally be activated and that contains the original titles and names, but it would be evaluated _additionally_ and in a second step, and for the already existing entries with the same ID it would only overwrite or "patch" the content XML attributes that are specified, and leave the ones of the XML attributes that are _not_ specified (like `country` etc) (i.e. not reset them).


I would say this is what actually was proposed. You can even now provide a "user_zzz.xml" and in there just override what you want to override.

Potential plan: 
When selecting a "foreign language" (in our case then "German" or ... another non-English language) the "res/db/.../localized/de/***" files are loaded after loading in the English ones. This extends the db to also contain German texts in the localization.
Dunno in which step the user based stuff should come in - and if they should be multilingual or also have "localized" subfolders etc.

**Comment by nittka** [comment]
I consider localization and "original names" to be different topics (although they could be approached similarly). My PR already contains a sample file. The current folder structure is `database/Default/...` with "official" files and a user subdirectory. This structure implies that potentially there could be an alterative database with the same structure (e.g. `database/MyCustomDatabase/...`) some time in the future. There should be no global localization but one specific for a database.

My proposal is to place a "lang"-directory with localization files for each language (`database/Default/lang/en.xml`) directly in the database's root. Those files contain localizations only for persons and roles (news/scripts/programmes all already support language tags). I also think that these files need not contain many entries - there need not be translations for all names: "Yams Pond" can stay the same everywhere. Translations make sense for names like "Svetlana Königin von Schweden" - only special cases.
Entries from the lang directory are automatically picked up when selecting a language and override ONLY names - other attributes sould be ignored (not even be present in those files - see the example and the code in the PR).

Concerning "original names". Historically they are placed as ignored attributes in the regular database files. We now face the following problem. If we want to "simplify" switching to real names, there are several approaches. My preference: splitting the persons.xml into real persons (and roles) and fictional ones. Only the "real" file gets original-tags for fictional ones an "original" does not make much sense (original fake and fake fake!?). That way the substitution has to be made only for one file (user files should only contain fictional content).

As a consequence, the lang-directory needs to contain only few entries which makes maintenance easier. If necessary, rather than having one lang directory with files containing translations with "name" and "name_original", I would favor a `lang_original` directory.

**Comment by scr0llbaer9000** [comment]
Ok that all sounds good.

> You could already now provide a "user_zzz.xml" and in there just override what you want to override from the original files

I didn't know that, and good to know. Especially who would know that the evaluation would reliably happen in alphabetical order.

> Only the "real" file gets original-tags for fictional ones an "original" does not make much sense (original fake and fake fake!?). That way the substitution has to be made only for one file (user files should only contain fictional content).

Ok, back to my original plan then after all. `:D`
But it sounded like @GWRon would have preferred the solution to treat original data like another language.

> I would favor a `lang_original` directory.

For original names that also need translation vs fictional names that need translation I'll have to see when I get my hands on it which will be the most practical approach.

> I am against automatically activating

Yes by activating I meant just copying a directory (with original data) into a place where it is evaluated by the game.

**Comment by nittka** [comment]
In the best case, the user file names really should not play a role for evaluation. The order of relevant "official" files is taken care of within the code (may have to be adapted when splitting up files). User files are read afterwards, so they can reference official data. The user files should define their own persons etc. for consistency or "common" entries should have been added to official files. The language directory is applied at the very end.

I think there has not been a process of making user entries "official" (like news collections or scripts).

I know that treating original data like another language would also be an option (with the player in mind). If doing that consistently, you would have to duplicate hundreds of entries, ensuring consistency (IDs, not switching two entries by chance) would be a huge effort. And for consistency, you would have to move the translations of movie titles (and descriptions?) also to those files. So maintenance would be a nightmare in my opinion (the keys in the property files give some indication, what they are about; a db id like "efak23-111-32.." tells you nothing and you cannot align the en.xml with the original data.
The advantage of the current situation is that original and changed name are in the same place. You see and can adapt them in one place, consistency is way easier to maintain.

If some players are real keen on playing with real names but not able to follow instructions for a handful of replacements - make the download to a replacement database available. The additional "translate person names"-feature can be used to deal with special cases (only).

**Comment by nittka** [comment]
Did you have a chance to look at the arguments and PR #902? A possible approach is only a couple of clicks away.
