### ISSUE TITLE
Adding a new variation of the "movie announcements" in news

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#905]
Because I had noticed some inconsistency between the German and the English version, and because more variation in news items is always good, I added a new "movie announcement" item with index 5 `NEWS_ANNOUNCE_MOVIE_DESCRIPTION5` to the `lang/news` files (commented out in languages other than German and English) in my current PR.

Can you check if the software already evaluates it? And if not, add it to the set so that it would appear in the game?

Alternatively, shouldn't things like this rather be in the `.xml` files? I know there is a special setting for news items that can only be triggered by code, which is the case here. Can this already be applied here? And if so, is it already possible to add a 6th, 7th, 8th,... variation there, without touching the `lang/news` files?

**Comment by nittka** [comment]
It seems you forgot to add the German and English version in the commit.
When "keys" with counters are used, the range of the counter is never passed as an argument. So if the framework is not broken, adding new variants should work out of the box. I have not checked whether there are problems when going two-digit.

I am not sure if using XML rather than the lang-files is really better. In this case it is certainly not possible at the moment. There has to be a hard-coded connection between the "event" and the news item, as you don't want to trigger some arbitrary news.

See also #125. More "ingame" news for movies, sports (more leagues and other regular events triggering ingame productions and news) etc. would be nice. But currently, the priorities are elsewhere.

**Comment by nittka** [comment]
I tested that generally more than 9 alternatives work (KEY0,..., KEY9, KEY10, KEY11).
Can this ticket be closed with this answer?

**Comment by scr0llbaer9000** [comment]
sure.
